// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using oc_catalog_audiovisuals_productions_backend.Context;

#nullable disable

namespace oc_catalog_audiovisuals_productions_backend.Migrations
{
    [DbContext(typeof(CatalogContext))]
    [Migration("20260411220649_FixTables")]
    partial class FixTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("oc_catalog_audiovisuals_productions_backend.Models.GenreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("oc_catalog_audiovisuals_productions_backend.Models.ProductionGenreModel", b =>
                {
                    b.Property<int>("ProductionId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("ProductionId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("ProductionsGenres");
                });

            modelBuilder.Entity("oc_catalog_audiovisuals_productions_backend.Models.ProductionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternativeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleasedYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Productions");
                });

            modelBuilder.Entity("oc_catalog_audiovisuals_productions_backend.Models.ProductionGenreModel", b =>
                {
                    b.HasOne("oc_catalog_audiovisuals_productions_backend.Models.GenreModel", "Genre")
                        .WithMany("ProductionsGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oc_catalog_audiovisuals_productions_backend.Models.ProductionModel", "Production")
                        .WithMany("ProductionsGenres")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("oc_catalog_audiovisuals_productions_backend.Models.GenreModel", b =>
                {
                    b.Navigation("ProductionsGenres");
                });

            modelBuilder.Entity("oc_catalog_audiovisuals_productions_backend.Models.ProductionModel", b =>
                {
                    b.Navigation("ProductionsGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
